version: '3.7'
services:
     elasticsearch:
       container_name: elasticsearch
       image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
       environment:
          - 'discovery.type=single-node'
          - 'ES_JAVA_OPTS=-Xms256M -Xmx256M'
          - 'xpack.license.self_generated.type=trial'
       ports:
          - 9200:9200
          - 9300:9300
       networks:
          - docker-elk
     logstash:
        image: docker.elastic.co/logstash/logstash:7.1.1
        container_name: logstash
        ports:
            - 5000:5000
            - 9600:9600
        networks: 
            - docker-elk
        volumes: 
            - type: bind
              source: /var/log/httpd/access_log
              target: /var/log/httpd/access_log
            - type: bind
              source: ./logstash/pipelines/
              target: /usr/share/logstash/pipeline
        depends_on: 
            -  elasticsearch
     kibana:
       container_name: kibana
       image: docker.elastic.co/kibana/kibana:7.1.1
       ports:
          - 5601:5601
       environment:
          - 'ELASTICSEARCH_HOSTS=http://elasticsearch:9200'
       networks:
          - docker-elk
       depends_on:
          - elasticsearch
networks:
  docker-elk:
    driver: bridge
